package game

import (
	"fmt"
	"image"
	"image/png"
	"os"
	"path/filepath"
)

// Lazy asset loading from assets/png generated by cmd/convert-assets.
// Only PNG outputs are used at runtime; original .img/.neo assets are not read.

type atlas struct {
	Tiles      []*image.RGBA   // tile_00.png .. tile_48.png
	BGTop      *image.RGBA     // obenplat.img.png (top plate)
	BGArea     *image.RGBA     // eispla2.img.png (game area plate)
	MenuPlate  *image.RGBA     // menuplat.img.png (menu button plate)
	Digits     [10]*image.RGBA // font digits 0..9 (16x15)
	HelpPlates []*image.RGBA   // 6 plates for help (64x16)
	Font47     []*image.RGBA   // 47 font glyphs (16x15)
	CharSheet  *image.RGBA     // rendered chars8 sheet if loaded from PNG
}

func loadPNG(path string) (*image.RGBA, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()
	m, err := png.Decode(f)
	if err != nil {
		return nil, err
	}
	// Convert to RGBA if needed
	if img, ok := m.(*image.RGBA); ok {
		return img, nil
	}
	b := m.Bounds()
	out := image.NewRGBA(b)
	for y := b.Min.Y; y < b.Max.Y; y++ {
		for x := b.Min.X; x < b.Max.X; x++ {
			out.Set(x, y, m.At(x, y))
		}
	}
	return out, nil
}

func (g *Game) tryLoadAtlas() {
	const maxTiles = 49
	a := &atlas{}

	// Tiles
	for i := 0; i < maxTiles; i++ {
		if img, err := loadPNG(filepath.Join("assets", "png", sprintfTile(i))); err == nil {
			a.Tiles = append(a.Tiles, img)
		}
	}

	// Background plates
	if img, err := loadPNG(filepath.Join("assets", "png", "obenplat.img.png")); err == nil {
		a.BGTop = img
	}
	if img, err := loadPNG(filepath.Join("assets", "png", "eispla2.img.png")); err == nil {
		a.BGArea = img
	}
	if img, err := loadPNG(filepath.Join("assets", "png", "menuplat.img.png")); err == nil {
		a.MenuPlate = img
	}

	// FONT2 digits and glyphs from PNG
	for i := 0; i < 10; i++ {
		if img, err := loadPNG(filepath.Join("assets", "png", "font2", fmt.Sprintf("digit_%d.png", i))); err == nil {
			a.Digits[i] = img
		}
	}
	a.Font47 = make([]*image.RGBA, 47)
	for i := 0; i < 47; i++ {
		if img, err := loadPNG(filepath.Join("assets", "png", "font2", fmt.Sprintf("glyph_%02d.png", i))); err == nil {
			a.Font47[i] = img
		}
	}

	// Help plates (6 states)
	for i := 0; i < 6; i++ {
		if img, err := loadPNG(filepath.Join("assets", "png", "help", fmt.Sprintf("help_%d.png", i))); err == nil {
			a.HelpPlates = append(a.HelpPlates, img)
		}
	}

	// chars8 sheet
	if img, err := loadPNG(filepath.Join("assets", "png", "chars8_sheet.png")); err == nil {
		a.CharSheet = img
	}

	g.atlas = a
}

func sprintfTile(i int) string { return "tile_" + itoa2(byte(i)) + ".png" }
